config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create]
  resources :subs, except: [:destroy]
  resources :posts, except: [:destroy, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :sub_id, presence: true

  has_many :post_subs, inverse_of: :post, dependent: :destroy
  has_many :subs, through: :post_subs, source: :sub

  belongs_to :author,
    foreign_key: :user_id,
    class_name: 'User',
    inverse_of: :posts
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :description, :name, presence: true
  validates :name, uniqueness: true

  has_many :post_subs, inverse_of: :sub, dependent: :destroy
  has_many :posts, through: :post_subs, source: :post

  belongs_to :moderator,
    foreign_key: :moderator_id,
    class_name: 'User',
    inverse_of: :subs
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validates :session_token, :name, uniqueness: true

  attr_reader :password

  after_initialize :ensure_session_token

  has_many :posts,
    foreign_key: :user_id,
    class_name: 'Post'

  def self.find_by_credentials(name, password)
    user = User.find_by(name: name)
    user.try(:is_password?, password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(16)
  end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= User.find_by(session_token: session[:token])
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    session[:token] = user.reset_session_token!
  end

  def sign_out
    current_user.try(:reset_session_token!)
    session[:token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end

  def require_signed_out!
    redirect_to user_url(current_user) if signed_in?
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_signed_in!, except: [:show]
  before_action :require_user_owns_post!, only: [:edit, :update]

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
    end
  end

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  private
  def post_params
    params.require(:post).permit(
    :url, :title, :content, :user_id, sub_ids: []
    )
  end

  def require_user_owns_post!
    return if current_user.posts.find_by(id: params[:id])
    render json: 'Forbidden', status: :forbidden
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_signed_out!, only: [:new, :create]
  before_action :require_signed_in!, only: [:destroy]

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:name],
      params[:user][:password]
    )

    if @user
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = ['Invalid username or password']
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_signed_in!, except: [:index, :show]
  before_action :require_user_owns_sub!, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
    @sub = Sub.new
    render :new
  end

  def show
    @sub = Sub.find(params[:id])
    render :show
  end

  def create
    @sub = current_user.subs.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to @sub
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def edit
    @sub = Sub.find(params[:id])
    render :edit
  end

  private
  def require_user_owns_sub!
    return if current_user.subs.find_by(id: params[:id])
    render json: 'Forbidden', status: :forbidden
  end

  def sub_params
    params.require(:sub).permit(:name, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_signed_in!, only: [:show]
  before_action :require_signed_out!, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% action_url = post.persisted? ? post_url(post) : posts_url %>
<% http_method = post.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title:
    <input name="post[title]" value="<%= post.title %>">
  </label>
  <br>

  <label>
    URL:
    <input name="post[url]" value="<%= post.url %>">
  </label>
  <br>

  <label>
    Content:
    <textarea name="post[content]"><%= post.content %></textarea>
  </label>
  <br>

  <input type="hidden" name="post[sub_ids][]" value="">
  <% Sub.all.each do |sub| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub.id %>"
        <%= "checked" if post.sub_ids.include?(sub.id) %>>
      <%= sub.name %>
    </label>
    <br>
  <% end %>

  <input type="Submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<h1>Edit Post!</h1>

<%= render "form", post: @post %>

app/views/posts/new.html.erb
<h1>New Post!</h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1>
  (<%= @post.votes %>)
  <a href="<%= post_url(@post) %>"><%= @post.title %></a> by
  <%= @post.author.name %>
</h1>

<br>
<b>Subs</b>
<ul>
  <% @post.subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.name %></a></li>
  <% end %>
</ul>

<a href="<%= edit_post_url(@post) if @post.author == current_user %>">Edit</a>

app/views/subs/_form.html.erb
<% action_url = sub.persisted? ? sub_url(sub) : subs_url %>
<% http_method = sub.persisted? ? "PATCH" : "POST" %>

<form action="<%= action_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="<%= http_method %>">

  <label>
    Name
    <input name="sub[name]" value="<%= sub.name %>">
  </label>
  <br>

  <label>
    Description
    <textarea name="sub[description]"><%= sub.description %></textarea>
  </label>

  <input type="submit" value="Submit!">
</form>

app/views/subs/edit.html.erb
<h1>Edit your Sub</h1>

<%= render "form", sub: @sub %>

app/views/subs/index.html.erb
<h1>All the Subs!</h1>

<ul>
  <% @subs.each do |sub| %>
    <li><a href="<%= sub_url(sub) %>"><%= sub.name %></a><br></li>
  <% end %>
</ul>

app/views/subs/new.html.erb
<h1>Create a new sub!</h1>
<%= render "form", sub: @sub %>

app/views/subs/show.html.erb
<h1>
  <%= @sub.name %>
</h1>


<b>Description</b>
<p><%= @sub.description %></p>

<a href="<%= new_post_url %>">Make New Post!</a>

<ul>
  <% @sub.posts.each do |post| %>
    <li>(<%= post.votes %>) <a href="<%= post_url(post) %>"><%= post.title %></a></li>
  <% end %>
</ul>
<a href="<%= edit_sub_url(@sub) if @sub.moderator == current_user %>">Edit</a>

app/views/users/new.html.erb
<h1>New User!</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>
    Username
    <input type="text" name="user[name]" value="<%= @user.name %>">
  </label>

  <label>
    Password
    <input type="password" name="user[password]" value="">
  </label>
  
  <input type="submit" value="create user">
</form>